### ISSUE TITLE
Seems to be interfering with jekyll-paginate on home

### ISSUE THREAD

**Issue by vallieres** [jguyomard/jekyll-paginate-categories#3]
Hello,

When removing the gem from both _config.yml and Gemfile, I get a proper index page on the root of my site (with a paginator.posts that lists all posts). When I enable the paginate-categories gem, I get a broken homepage.

With jekyll-paginate-categories
https://d17oy1vhnax1f7.cloudfront.net/items/072q2Q3R1K1L293w2a3y/Image%202017-01-02%20at%206.17.23%20PM.png

Without jekyll-paginate-categories
https://d17oy1vhnax1f7.cloudfront.net/items/1X0p3G12302S33120821/Image%202017-01-02%20at%206.21.08%20PM.png?v=169eb015

index.html
```---
layout: default
bodyclass: home
title: Home
---

  <!-- Section -->
  <section>
    <header class="major">
    {% if paginator.page == 1 %}
      <h3>Latest posts</h3>
    {% else %}
      <h3>Latest posts » Page {{ paginator.page }}</h3>
    {% endif%}
    </header>
    <div class="posts">
      {% for post in paginator.posts %}
        {% include homepage-post.html %}
      {% endfor %}
    </div>

    {% include pagination.html %}
  </section>
```

default.html
```
<!DOCTYPE html>
<html lang="en-CA">
  <head>
    {% include head.html %}
  </head>

  <body class="{% if page.bodyclass %}{{ page.bodyclass }}{% endif %}">

  		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
				<div id="main">
					<div class="inner">

            {% include header.html %}

            {% if paginator.previous_page == null and page.bodyclass != 'post' %}
              {% include feature.html %}
            {% endif %}

            {{ content }}

          </div> <!-- // inner -->
        </div> <!-- // main -->

      {% include sidebar.html %}

      {% include footer.html %}

```

_config.yml
```
# Pagination
paginate: 8 #6
paginate_path: "/page/:num"

paginate_category_basepath: '/category/:name/'
paginate_category_layout: 'category.html'
```

And a few lines of category.html. It does not use the same layout as the root index.html.
category.html
```
---
layout: single-archive
bodyclass: category
type: archive
---
```

**Comment by jguyomard** [comment]
Hello,

Thank you for this issue. I have tried to reproduce this bug, but have been unsuccessful. This is my files:


index.html
```html
---
layout: default
bodyclass: home
title: Home
---
 
  <!-- Section -->
  <section>
    <header class="major">
    {% if paginator.page == 1 %}
      <h3>Latest posts</h3>
    {% else %}
      <h3>Latest posts » Page {{ paginator.page }}</h3>
    {% endif%}
    </header>
    <div class="posts">
      {% for post in paginator.posts %}
	<h1>{{ post.title }}</h1>
        <div class="entry-content" itemprop="description">
          {{ post.excerpt }}
        </div>
      {% endfor %}
    </div>

    {% include pagination.html %}
  </section>
```

default.html
```html
<!DOCTYPE html>
<html>

  {% include head.html %}

  <body class="{% if page.bodyclass %}{{ page.bodyclass }}{% endif %}">

        <main>
            {{ content }}
        </main>
...
```

_config.yml
```yaml
paginate: 8 #6
paginate_path: "/page/:num"

paginate_category_basepath: '/category/:name/'
paginate_category_layout: 'category.html'
```

and it works well with Jekyll 3.2.1.

What is your Jekyll version?
Can you give me a complete list of your gems?

**Comment by vallieres** [comment]
I'm baffled by this, but in the end it does not seem to be related to your plugin.
If I change the order of the Gems in my Gemfile and _config.yml, it now works.

Before (breaking):
Gemfile
```
group :jekyll_plugins do
   gem "jekyll-feed"
   gem 'jekyll-gist'
   gem 'jekyll-archives'
   gem 'jekyll-paginate'
   gem 'jekyll-paginate-categories'
   gem 'jekyll-lunr-js-search'
end
```

_config.yml
```
gems:
  - kramdown
  - jekyll-watch
  - jekyll-gist
  - jekyll-paginate
  - jekyll-lunr-js-search
```

After (working):

Gemfile
```
group :jekyll_plugins do
   gem 'jekyll-lunr-js-search'
   gem "jekyll-feed"
   gem 'jekyll-gist'
   gem 'jekyll-archives'
   gem 'jekyll-paginate'
   gem 'jekyll-paginate-categories'
end
```

_config.yml
```
gems:
  - kramdown
  - jekyll-lunr-js-search
  - jekyll-watch
  - jekyll-gist
  - jekyll-paginate
```

After looking at a bunch of sites hosted on Github with the source available I realized that it was not my code directly. Two days ago it worked before adding the search so I removed the search and left both jekyll-paginate and jekyll-paginate-category. It worked. I was (and still am) baffled.

So in a desperate attempt I moved the lunr seach plugin to the top and it now works. Sorry for wasting your time on this.

Great job on the plugin by the way! The cleanest implementation of the category pagination to my eyes!

**Comment by jguyomard** [comment]
Thank you for this reply, i can now close this issue :)
Have a good day
